# Generated by Django 3.2.6 on 2021-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_desc',
            field=models.TextField(null=True),
        ),
    ]
