# Generated by Django 3.2.6 on 2021-08-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_short_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='short_desc',
        ),
    ]
