# Generated by Django 3.2.6 on 2021-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(null=True),
        ),
    ]
